chore: fix bug with buildspec.

diff --git a/packages/gp-api/deploy/buildspec.yml b/packages/gp-api/deploy/buildspec.yml
--- a/packages/gp-api/deploy/buildspec.yml
+++ b/packages/gp-api/deploy/buildspec.yml
@@ -25,13 +25,7 @@ phases:
 
   post_build:
     commands:
-      - |
-        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
-          echo "Build completed successfully!"
-        else
-          echo "Build failed!"
-          exit 1
-        fi
+      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo "Build completed successfully!"; else echo "Build failed!" && exit 1; fi
 
 # cache:
 #   paths:
